/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c DemoIf -p /home/suman/sample_mob_apps/dbustutorial/src/demoif.h:/home/suman/sample_mob_apps/dbustutorial/src/demoif.cpp com.nokia.Demo.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "/home/suman/sample_mob_apps/dbustutorial/src/demoif.h"

/*
 * Implementation of interface class DemoIf
 */

DemoIf::DemoIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DemoIf::~DemoIf()
{
}

